name: scan_bibli
description: Bibliothèque personnelle avec scanner ISBN
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.3.0
  mobile_scanner: ^5.1.1
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  http: ^1.2.0
  google_fonts: ^6.1.0
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
